version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    target-branch: "develop"

    # Agrupar todas as dependências em um único PR (opcional)
    groups:
      all-deps:
        patterns:
          - "*"

    # Configura mensagem de commit/PR
    commit-message:
      prefix: "build(deps)"
